import { ColumnDefinition } from "@/example/types/tableTypes";

/**
 * 購入情報データの型定義（UserData型に合わせて拡張）
 */
export interface PurchaseData {
  id: number;
  userId: number;
  productName: string;
  color: string;
  price: number;
  quantity: number;
  totalAmount: number;
  // UserData型に合わせて追加フィールド
  name: string;
  email: string;
  role: string;
  notes: string;
}

/**
 * ユーザーテーブル用のカラム定義
 */
export const userColumnDefinitions: ColumnDefinition[] = [
  {
    key: "id",
    label: "ユーザーID",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "center",
    cellAlign: "center",
    defaultWidth: 100,
    minWidth: 80,
    maxWidth: 120,
  },
  {
    key: "name",
    label: "ユーザー名",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "left",
    cellAlign: "left",
    defaultWidth: 150,
    minWidth: 100,
    maxWidth: 300,
  },
  {
    key: "email",
    label: "メールアドレス",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "left",
    cellAlign: "left",
    defaultWidth: 250,
    minWidth: 200,
    maxWidth: 400,
  },
  {
    key: "role",
    label: "会員種別",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "center",
    cellAlign: "center",
    defaultWidth: 120,
    minWidth: 100,
    maxWidth: 200,
  },
  {
    key: "lastPurchaseDate",
    label: "購入日付",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "center",
    cellAlign: "center",
    defaultWidth: 120,
    minWidth: 100,
    maxWidth: 150,
  },
];

/**
 * 購入ユーザーデータ
 */
export const userData = [
  {
    id: 1,
    name: "田中太郎",
    email: "tanaka.taro@gmail.com",
    role: "VIP会員",
    status: "アクティブ",
    department: "東京都",
    notes: "高額購入者。ユニクロのヘビーユーザー。",
    lastPurchaseDate: "2024-01-15",
  },
  {
    id: 2,
    name: "佐藤花子",
    email: "sato.hanako@yahoo.co.jp",
    role: "一般会員",
    status: "アクティブ",
    department: "大阪府",
    notes: "ファッション好きの若い女性。",
    lastPurchaseDate: "2024-01-30",
  },
  {
    id: 3,
    name: "鈴木一郎",
    email: "suzuki.ichiro@outlook.com",
    role: "一般会員",
    status: "アクティブ",
    department: "神奈川県",
    notes: "ビジネスカジュアルを好む会社員。",
    lastPurchaseDate: "2024-01-18",
  },
  {
    id: 4,
    name: "高橋美咲",
    email: "takahashi.misaki@hotmail.com",
    role: "プレミアム会員",
    status: "アクティブ",
    department: "愛知県",
    notes: "オンラインショッピングの常連客。",
    lastPurchaseDate: "2024-02-01",
  },
  {
    id: 5,
    name: "山田次郎",
    email: "yamada.jiro@icloud.com",
    role: "一般会員",
    status: "アクティブ",
    department: "福岡県",
    notes: "カジュアルウェアを中心に購入。",
    lastPurchaseDate: "2024-01-10",
  },
  {
    id: 6,
    name: "伊藤健太",
    email: "ito.kenta@docomo.ne.jp",
    role: "一般会員",
    status: "アクティブ",
    department: "北海道",
    notes: "アウトドア系の商品を好む。",
    lastPurchaseDate: "2024-01-25",
  },
  {
    id: 7,
    name: "渡辺さくら",
    email: "watanabe.sakura@softbank.ne.jp",
    role: "一般会員",
    status: "アクティブ",
    department: "宮城県",
    notes: "学生向けの商品を中心に購入。",
    lastPurchaseDate: "2024-01-28",
  },
];

/**
 * 購入情報テーブル用のカラム定義
 */
export const purchaseColumnDefinitions: ColumnDefinition[] = [
  {
    key: "userId",
    label: "ユーザーID",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "center",
    cellAlign: "center",
    defaultWidth: 100,
    minWidth: 80,
    maxWidth: 120,
  },
  {
    key: "id",
    label: "商品ID",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "center",
    cellAlign: "center",
    defaultWidth: 80,
    minWidth: 60,
    maxWidth: 120,
  },
  {
    key: "productName",
    label: "商品名",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "left",
    cellAlign: "left",
    defaultWidth: 200,
    minWidth: 150,
    maxWidth: 400,
  },
  {
    key: "color",
    label: "カラー",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "center",
    cellAlign: "center",
    defaultWidth: 100,
    minWidth: 80,
    maxWidth: 150,
  },
  {
    key: "price",
    label: "定価",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "right",
    cellAlign: "right",
    defaultWidth: 100,
    minWidth: 80,
    maxWidth: 150,
  },
  {
    key: "quantity",
    label: "購入点数",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "center",
    cellAlign: "center",
    defaultWidth: 100,
    minWidth: 80,
    maxWidth: 120,
  },
  {
    key: "totalAmount",
    label: "合計金額",
    sortable: true,
    resizable: true,
    wrapText: false,
    headerAlign: "right",
    cellAlign: "right",
    defaultWidth: 120,
    minWidth: 100,
    maxWidth: 150,
  },
];

/**
 * 購入情報データ
 */
export const purchaseData: PurchaseData[] = [
  {
    id: 1,
    userId: 1,
    productName: "フリースジャケット",
    color: "ネイビー",
    price: 2990,
    quantity: 1,
    totalAmount: 2990,
    name: "フリースジャケット",
    email: "tanaka.taro@gmail.com",
    role: "VIP会員",
    notes: "人気商品のフリースジャケット。サイズL",
  },
  {
    id: 2,
    userId: 2,
    productName: "ヒートテック インナー",
    color: "ブラック",
    price: 1490,
    quantity: 2,
    totalAmount: 2980,
    name: "ヒートテック インナー",
    email: "sato.hanako@yahoo.co.jp",
    role: "一般会員",
    notes: "冬の定番商品。カラー：ブラック",
  },
  {
    id: 3,
    userId: 3,
    productName: "ジーンズ スリムフィット",
    color: "インディゴ",
    price: 3990,
    quantity: 1,
    totalAmount: 3990,
    name: "ジーンズ スリムフィット",
    email: "suzuki.ichiro@outlook.com",
    role: "一般会員",
    notes: "ビジネスカジュアル用ジーンズ。サイズ32",
  },
  {
    id: 4,
    userId: 4,
    productName: "カシミアセーター",
    color: "ベージュ",
    price: 7990,
    quantity: 1,
    totalAmount: 7990,
    name: "カシミアセーター",
    email: "takahashi.misaki@hotmail.com",
    role: "プレミアム会員",
    notes: "高級素材のカシミアセーター。カラー：ベージュ",
  },
  {
    id: 5,
    userId: 5,
    productName: "ポロシャツ",
    color: "ホワイト",
    price: 1990,
    quantity: 3,
    totalAmount: 5970,
    name: "ポロシャツ",
    email: "yamada.jiro@icloud.com",
    role: "一般会員",
    notes: "夏の定番ポロシャツ。カラー：ホワイト",
  },
  {
    id: 6,
    userId: 6,
    productName: "ダウンジャケット",
    color: "ブラック",
    price: 5990,
    quantity: 1,
    totalAmount: 5990,
    name: "ダウンジャケット",
    email: "ito.kenta@docomo.ne.jp",
    role: "一般会員",
    notes: "アウトドア用ダウンジャケット。防寒性重視",
  },
  {
    id: 7,
    userId: 7,
    productName: "スウェットパンツ",
    color: "グレー",
    price: 2990,
    quantity: 2,
    totalAmount: 5980,
    name: "スウェットパンツ",
    email: "watanabe.sakura@softbank.ne.jp",
    role: "一般会員",
    notes: "学生向けカジュアルパンツ。サイズS",
  },
  {
    id: 8,
    userId: 1,
    productName: "コットンTシャツ",
    color: "ネイビー",
    price: 990,
    quantity: 5,
    totalAmount: 4950,
    name: "コットンTシャツ",
    email: "tanaka.taro@gmail.com",
    role: "VIP会員",
    notes: "基本のコットンTシャツ。カラー：ネイビー",
  },
  {
    id: 9,
    userId: 2,
    productName: "ウールコート",
    color: "ブラック",
    price: 8990,
    quantity: 1,
    totalAmount: 8990,
    name: "ウールコート",
    email: "sato.hanako@yahoo.co.jp",
    role: "一般会員",
    notes: "フォーマル用ウールコート。サイズM",
  },
  {
    id: 10,
    userId: 4,
    productName: "レギンス",
    color: "ブラック",
    price: 1990,
    quantity: 2,
    totalAmount: 3980,
    name: "レギンス",
    email: "takahashi.misaki@hotmail.com",
    role: "プレミアム会員",
    notes: "スポーツ用レギンス。カラー：ブラック",
  },
];
